# the path and file name of the keepass database
# $HOME/devel/go/kpasscli/
database_path:  bitwarden

# the default output for the password, can be 'stdout' or 'clipboard'
default_output: stdout

# file which contains the password to open the keepass db
password_file: ~/bwpasswd
# or
# the path to the executable, that returns the password to open the keepass database
password_executable:
